#!/usr/bin/env bash
# Configures a new ubuntu machine by installing

sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

# start nginx service
sudo service nginx start

# allowing nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
print %s "server {
	listen 80;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 http://sirgitau.tech/;
	}

	error_page 404 / 404.html;
	location /404 {
	   root /etc/nginx/html;
	   internal;
        }
}" >> /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
