#!/usr/bin/env bash

# Install loadbalance
sudo apt-get -y update
sudo apt-get install haproxy -y

# Change file ownership
sudo chmod $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend MyHaproxy
   bind *:80
   mode http
   default_backend serve1

backend servers
  balance roundrobin
  server 266533-web-01 34.227.90.116:80 check
  server 266533-web-02 34.239.249.63:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
