#!/usr/bin/env bash

sudo ufw enable
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

sudo echo
":PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" >> /etc/ufw/before.rules
